# Application
spring.application.name=spring-gift

# H2 DB
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=

# Security/JWT
jwt.secret=Yn2kjibddFAWtnPJ2AFLl8WXmohJMCvigQggaEypa5E=

# JPA/Hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Logging
logging.level.org.hibernate.orm.jdbc.bind=TRACE
